"""Initial commit

Revision ID: 3b893dfbfa78
Revises: 
Create Date: 2024-10-24 12:02:22.581641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b893dfbfa78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donormodel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('department', sa.Enum('BANGLA', 'ENGLISH', 'HISTORY', 'ISLAMIC_HISTORY_AND_CULTURE', 'PHILOSOPHY', 'FINE_ARTS', 'ARABIC', 'PALI', 'ISLAMIC_STUDIES', 'DRAMATICS', 'PERSIAN_LANGUAGE_AND_LITERATURE', 'EDUCATION_AND_RESEARCH', 'MODERN_LANGUAGES', 'SANSKRIT', 'MUSIC', 'BANGLADESH_STUDIES', 'PHYSICS', 'CHEMISTRY', 'MATHEMATICS', 'STATISTICS', 'FORESTRY_AND_ENVIRONMENTAL_SCIENCES', 'APPLIED_CHEMISTRY_AND_CHEMICAL_ENGINEERING', 'ACCOUNTING', 'MANAGEMENT', 'FINANCE', 'MARKETING', 'HUMAN_RESOURCE_MANAGEMENT', 'BANKING_AND_INSURANCE', 'ECONOMICS', 'POLITICAL_SCIENCE', 'SOCIOLOGY', 'PUBLIC_ADMINISTRATION', 'ANTHROPOLOGY', 'INTERNATIONAL_RELATIONS', 'COMMUNICATION_AND_JOURNALISM', 'DEVELOPMENT_STUDIES', 'CRIMINOLOGY_AND_POLICE_SCIENCE', 'LAW', 'ZOOLOGY', 'BOTANY', 'GEOGRAPHY_AND_ENVIRONMENTAL_STUDIES', 'BIOCHEMISTRY_AND_MOLECULAR_BIOLOGY', 'MICROBIOLOGY', 'SOIL_SCIENCE', 'GENETIC_ENGINEERING_AND_BIOTECHNOLOGY', 'PSYCHOLOGY', 'PHARMACY', 'COMPUTER_SCIENCE_AND_ENGINEERING', 'ELECTRICAL_AND_ELECTRONIC_ENGINEERING', 'PHYSICAL_EDUCATION_AND_SPORTS_SCIENCE', 'MARINE_SCIENCES', 'OCEANOGRAPHY', 'FISHERIES', name='departmentsenum'), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('district', sa.Enum('BAGERHAT', 'BANDARBAN', 'BARGUNA', 'BARISAL', 'BHOLA', 'BOGURA', 'BRAHMANBARIA', 'CHANDPUR', 'CHAPAINAWABGANJ', 'CHATTOGRAM', 'CHUADANGA', 'COXS_BAZAR', 'CUMILLA', 'DHAKA', 'DINAJPUR', 'FARIDPUR', 'FENI', 'GAIBANDHA', 'GAZIPUR', 'GOPALGANJ', 'HABIGANJ', 'JAMALPUR', 'JESSORE', 'JHALOKATI', 'JHENAIDAH', 'JOYPURHAT', 'KHAGRACHHARI', 'KHULNA', 'KISHOREGANJ', 'KURIGRAM', 'KUSHTIA', 'LAKSHMIPUR', 'LALMONIRHAT', 'MADARIPUR', 'MAGURA', 'MANIKGANJ', 'MEHERPUR', 'MOULVIBAZAR', 'MUNSHIGANJ', 'MYMENSINGH', 'NAOGAON', 'NARAIL', 'NARAYANGANJ', 'NARSINGDI', 'NATORE', 'NETROKONA', 'NILPHAMARI', 'NOAKHALI', 'PABNA', 'PANCHAGARH', 'PATUAKHALI', 'PIROJPUR', 'RAJBARI', 'RAJSHAHI', 'RANGAMATI', 'RANGPUR', 'SATKHIRA', 'SHARIATPUR', 'SHERPUR', 'SIRAJGANJ', 'SUNAMGANJ', 'SYLHET', 'TANGAIL', 'THAKURGAON', name='districtenum'), nullable=False),
    sa.Column('blood_group', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='bloodgroupenum'), nullable=False),
    sa.Column('academic_year', sa.Enum('YEAR_2010_2011', 'YEAR_2011_2012', 'YEAR_2012_2013', 'YEAR_2013_2014', 'YEAR_2014_2015', 'YEAR_2015_2016', 'YEAR_2016_2017', 'YEAR_2017_2018', 'YEAR_2018_2019', 'YEAR_2019_2020', 'YEAR_2020_2021', 'YEAR_2021_2022', 'YEAR_2022_2023', 'YEAR_2023_2024', 'YEAR_2024_2025', 'YEAR_2025_2026', 'YEAR_2026_2027', 'YEAR_2027_2028', 'YEAR_2028_2029', 'YEAR_2029_2030', 'YEAR_2030_2031', 'YEAR_2031_2032', 'YEAR_2032_2033', 'YEAR_2033_2034', 'YEAR_2034_2035', 'YEAR_2035_2036', 'YEAR_2036_2037', 'YEAR_2037_2038', 'YEAR_2038_2039', 'YEAR_2039_2040', 'YEAR_2040_2041', 'YEAR_2041_2042', 'YEAR_2042_2043', 'YEAR_2043_2044', 'YEAR_2044_2045', 'YEAR_2045_2046', 'YEAR_2046_2047', 'YEAR_2047_2048', 'YEAR_2048_2049', 'YEAR_2049_2050', name='academicyearenum'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('donated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donormodel_academic_year'), 'donormodel', ['academic_year'], unique=False)
    op.create_index(op.f('ix_donormodel_blood_group'), 'donormodel', ['blood_group'], unique=False)
    op.create_index(op.f('ix_donormodel_department'), 'donormodel', ['department'], unique=False)
    op.create_index(op.f('ix_donormodel_district'), 'donormodel', ['district'], unique=False)
    op.create_index(op.f('ix_donormodel_email'), 'donormodel', ['email'], unique=True)
    op.create_index(op.f('ix_donormodel_full_name'), 'donormodel', ['full_name'], unique=False)
    op.create_index(op.f('ix_donormodel_gender'), 'donormodel', ['gender'], unique=False)
    op.create_index(op.f('ix_donormodel_mobile'), 'donormodel', ['mobile'], unique=True)
    op.create_index(op.f('ix_donormodel_student_id'), 'donormodel', ['student_id'], unique=True)
    op.create_table('profilemodel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('employment_status', sa.Enum('STUDENT', 'EMPLOYED', 'UNEMPLOYED', name='employmentstatusenum'), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donormodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profilemodel')
    op.drop_index(op.f('ix_donormodel_student_id'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_mobile'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_gender'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_full_name'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_email'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_district'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_department'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_blood_group'), table_name='donormodel')
    op.drop_index(op.f('ix_donormodel_academic_year'), table_name='donormodel')
    op.drop_table('donormodel')
    # ### end Alembic commands ###
